---
- name: Expand rootfs
  ansible.builtin.import_playbook: ../bootstrap/00-expand-rootfs.yml

- name: Run system updates
  ansible.builtin.import_playbook: ../bootstrap/00-system-updates.yml

- name: Install observability agents
  ansible.builtin.import_playbook: ../bootstrap/00-observability-agents.yml

- name: Configure restic backups in 01-backup-lxc
  hosts: 01-backup-lxc
  become: true
  tasks:
    - name: Deploy restic_backup role
      ansible.builtin.import_role:
        name: restic_backup
