---
- name: Expand rootfs
  ansible.builtin.import_playbook: ../bootstrap/00-expand-rootfs.yml

- name: Run system updates
  ansible.builtin.import_playbook: ../bootstrap/00-system-updates.yml

- name: Install observability agents
  ansible.builtin.import_playbook: ../bootstrap/00-observability-agents.yml

- name: Configure Tailscale subnet router in 01-tailscale-lxc
  hosts: 01-tailscale-lxc
  become: true
  tasks:
    - name: Import tailscale role
      ansible.builtin.import_role:
        name: tailscale
