---
- name: Expand rootfs
  ansible.builtin.import_playbook: ../bootstrap/00-expand-rootfs.yml

- name: Run system updates
  ansible.builtin.import_playbook: ../bootstrap/00-system-updates.yml

- name: Install observability agents
  ansible.builtin.import_playbook: ../bootstrap/00-observability-agents.yml

- name: Install torrent client in 01-torrent-lxc
  hosts: 01-torrent-lxc
  become: true
  tasks:
    - name: Import qbittorrent role
      ansible.builtin.import_role:
        name: qbittorrent
