#!/usr/bin/env python3
"""
generate-inventory.py — regenerate ansible/inventory.ini from Terraform variable defaults.

Because all IPs in this homelab are statically assigned (DHCP reservations + cloud-init),
the source of truth is the default values in each stack's variables.tf.  This script
parses those defaults and writes a fresh inventory.ini, keeping the file in sync
whenever a stack is renamed or its IP is changed.

Usage:
    python3 scripts/setup/generate-inventory.py
    # or to preview without writing:
    python3 scripts/setup/generate-inventory.py --dry-run
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent
TF_ROOT = REPO_ROOT / "infra-proxmox" / "terraform"
INVENTORY_PATH = REPO_ROOT / "ansible" / "inventory.ini"

ANSIBLE_USER = "toomhorvath"
SSH_KEY = "~/.ssh/toomhorvath"

# Each entry: (stack_dir, group_name, name_var, ip_var)
STACKS = [
    ("01-media-vm", "media_vm", "name", "ip_address"),
    ("01-myapps-vm", "myapps_vm", "name", "ip_address"),
    (
        "01-torrent-lxc",
        "torrent_lxc",
        "qbittorrent_lxc_name",
        "qbittorrent_lxc_ip_address",
    ),
    (
        "01-observability-lxc",
        "observability_lxc",
        "observability_lxc_name",
        "observability_lxc_ip_address",
    ),
    ("01-backup-lxc", "backup_lxc", "backup_lxc_name", "backup_lxc_ip_address"),
    ("01-edge-lxc", "edge_lxc", "cloudflared_lxc_name", "cloudflared_lxc_ip_address"),
    ("01-dns-lxc", "dns_lxc", "dns_lxc_name", "dns_lxc_ip_address"),
    (
        "01-reverse-proxy-lxc",
        "reverse_proxy_lxc",
        "reverse_proxy_lxc_name",
        "reverse_proxy_lxc_ip_address",
    ),
    (
        "01-tailscale-lxc",
        "tailscale_lxc",
        "tailscale_lxc_name",
        "tailscale_lxc_ip_address",
    ),
    # Podman, not Docker -- deliberately absent from DOCKER_HOSTS_CHILDREN below.
    ("01-unifi-vm", "unifi_vm", "name", "ip_address"),
    ("01-code-lxc", "code_lxc", "code_lxc_name", "code_lxc_ip_address"),
]

# Groups whose members run Docker (used in playbooks via docker_hosts:children)
DOCKER_HOSTS_CHILDREN = [
    "media_vm",
    "torrent_lxc",
    "myapps_vm",
    "observability_lxc",
]


def parse_default(variables_tf: Path, var_name: str) -> str:
    """Extract the default value of a Terraform variable from variables.tf."""
    text = variables_tf.read_text()
    # Match: variable "var_name" { ... default = "value" ... }
    # The block may span multiple lines; we look for the default line within the block.
    pattern = rf'variable\s+"{re.escape(var_name)}"\s*\{{[^}}]*?default\s*=\s*"([^"]+)"'
    m = re.search(pattern, text, re.DOTALL)
    if not m:
        raise ValueError(
            f"Could not find default for variable '{var_name}' in {variables_tf}"
        )
    return m.group(1)


def strip_prefix_len(ip_with_prefix: str) -> str:
    """192.168.1.70/24  →  192.168.1.70"""
    return ip_with_prefix.split("/")[0]


def build_inventory() -> str:
    lines: list[str] = [
        "# This file is auto-generated by scripts/setup/generate-inventory.py.",
        "# Do not edit by hand — change the Terraform variable defaults instead,",
        "# then re-run:  python3 scripts/setup/generate-inventory.py",
        "",
    ]

    group_members: dict[str, list[str]] = {}

    for stack_dir, group, name_var, ip_var in STACKS:
        variables_tf = TF_ROOT / stack_dir / "variables.tf"
        if not variables_tf.exists():
            print(
                f"WARNING: {variables_tf} not found — skipping {stack_dir}",
                file=sys.stderr,
            )
            continue

        host_name = parse_default(variables_tf, name_var)
        ip_with_prefix = parse_default(variables_tf, ip_var)
        ip = strip_prefix_len(ip_with_prefix)

        lines.append(f"[{group}]")
        lines.append(
            f"{host_name} ansible_host={ip}"
            f" ansible_user={ANSIBLE_USER}"
            f" ansible_ssh_private_key_file={SSH_KEY}"
        )
        lines.append("")
        group_members[group] = [host_name]

    lines.append("[docker_hosts:children]")
    lines.extend(DOCKER_HOSTS_CHILDREN)
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true", help="Print to stdout instead of writing"
    )
    args = parser.parse_args()

    inventory = build_inventory()

    if args.dry_run:
        print(inventory)
    else:
        INVENTORY_PATH.write_text(inventory)
        print(f"Wrote {INVENTORY_PATH}")


if __name__ == "__main__":
    main()
